apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: assignment2
  labels:
    app: employees
spec:
  containers:
    - name: web
      image: 860572194478.dkr.ecr.us-east-1.amazonaws.com/assignment2-ecr-app:v0.1
      ports:
      - containerPort: 8080       # The web app listens on port 8080
      env:
      - name: DBHOST
        value: "mysql-service"
      - name: DBPORT
        value: "3306"
      - name: DBUSER
        value: "root"
      - name: DBPWD
        value: "pw"
  imagePullSecrets:
  - name: regcred