
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: assignment2
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080          # Internal service port
      targetPort: 8080    # Container port
      nodePort: 30000     # External port on the node
